### ISSUE TITLE
Consolidation of use of Triangle: continued

### ISSUE THREAD

**Issue by j-fu** [j-fu/TriangleRaw.jl#1]
@konsim83, @furio,  @SimonDanisch: let us continue the discussion from [VoronoiFVM](https://github.com/j-fu/VoronoiFVM.jl/issues/2) here.

**Comment by j-fu** [comment]
There are some things to be discussed:
- @konsim83, @furio now are collaboraters
- All number information is in the arrays in the triangulateio struct, no extra fields for point numbers etc. Currently, an "empty" triangulateio consists of zero length arrays which are thrown away if something is put into the structure. In one sense it is much cleaner (no danger of mismatch), OTOH it is a bit weird to throw the arrays away. We probably could work here with undefined fields, I don't have much experience with that.
- I did an interface to the triunsuitable  refinement callback.
- Build scripts now just call the compiler, no need to work with the makefiles etc.
- Windows build is broken. I have not much experience here. I could test things on a Win10 VM however.
- Any experience with the new Pkg1.3 artifacts system ? It might come in handy here, though Triangle anyway is benign with compiling
- I didn't add any flag handling with booleans. I someone volunteers... - I have no time to go deeper into this, because it is a bit delicate... I very much rely on the string based interface anyway.
- How do we proceed with the renaming ?

**Comment by j-fu** [comment]
Meanwhile I researched two things:
- The TetGen.jl package IMHO provides the access to basic TetGen in the way I imagine (i.e. the higher level methods don't seem to prevent to call tetrahedralize with the original tetgen input.)
- Moreover, it uses artefacts. This should be done here as well (and there is the new artifacts system)
I'll try to figure this out...

I very much would like to continue with this package (I need it in VoronoiFVM), so I would like to start registering soon, maybe then under this name...

**Comment by j-fu** [comment]
Hi @furio, @konsim83: update of the plan
- We should figure out the name issue. Plan A was to use Triangle.jl as @furio principally agreed to use this name. However it might be that this becomes too complicated for users of the existing Triangle.jl, so plan B is to rename and register TriangleRaw as TriangulateIO.jl after the data structure it exports. I very much like to have this in order to continue my work, so I would start the registration process next week (e.g. Tuesday night) unless we can settle plan A.
- After registration I would set up the binary builder stuff based on the [new artifacts system](https://julialang.org/blog/2019/11/artifacts).  For simplicity I would keep the triangle.c sources in the repo together with the triunsuitable.c (alternatively we could download them from the quake page). This will create a <whatever_ name>.jll package which can be used upon installation.  The setup for this (on travis) will work only for 1.3. but AFAIK the generated jll will work for 1.x . As a result we in particular will have  a windows dll which  is independent of the compiler (they do it by cross compilation with gcc for mingw).
- Concerning the API I intend to rename the data structures in CamelCase manner. Moreover I think @konsim83 was right nevetheless to keep numberofedges etc. in the julia data structure as there even for nonzero numberofedges the edgelist might be empty. My idea of this package is to be as close to triangle as possible, so i might modify the data structure accordingly.
- I would not mind higher level APIs on top of the basic one as long as they don't draw in large dependencies. 
- Oh and once it's done we might say hi to Jonathan Shewchuk and ask him if he could put a link on his page.

**Comment by SimonDanisch** [comment]
Let me know if you need any help with BinaryBuilder!

**Comment by konsim83** [comment]
> We should figure out the name issue. Plan A was to use Triangle.jl as @furio principally agreed to use this name. However it might be that this becomes too complicated for users of the existing Triangle.jl, so plan B is to rename and register TriangleRaw as TriangulateIO.jl after the data structure it exports. I very much like to have this in order to continue my work, so I would start the registration process next week (e.g. Tuesday night) unless we can settle plan A.

I suggest to name it according to the structures that are planned to be created by the package. Both triangle and TetGen are packages that build simplicial meshes. Suggestion: **SimplexMesh.jl**?

Question @j-fu  can TetGen refine locally? If yes how? Triangle does so by employing rgb refinement but AFAIK coarsening may be difficult.

In general I think that before investing any time one should figure out the scope of the package (AMR with simplicial meshes?).

I also suggest, as @j-fu did, to bundle triangle.c and TetGen (if desired).

>Concerning the API I intend to rename the data structures in CamelCase manner. Moreover I think @konsim83 was right nevetheless to keep numberofedges etc. in the julia data structure as there even for nonzero numberofedges the edgelist might be empty. My idea of this package is to be as close to triangle as possible, so i might modify the data structure accordingly.

I agree, designing the interface being close to the data structures of triangle is a good idea. I am not really an expert in Julia to be honest but is there a way to hide the internals of the data structures and write acessors/iterators to relevant data instances?

>I would not mind higher level APIs on top of the basic one as long as they don't draw in large dependencies.

Having both is usually a good idea.

**Comment by j-fu** [comment]
> Let me know if you need any help with BinaryBuilder!

Oh thanks, sure. I want to learn how it works though, so I will try this first on my own.

Would it be possible to register this package under JuliaGeometry, or does it make sense to register first and move then ?

**Comment by SimonDanisch** [comment]
Btw, @sjkelly might be interested in this as well :) 
Would be great to move it to JuliaGeometry!

**Comment by sjkelly** [comment]
I'm not too familiar with the BInaryBuilder ecosystem. I have been using TetGen.jl quite successfully for my masters work thanks to @SimonDanisch . I have some examples of using TetGen here: https://github.com/sjkelly/DistMesh.jl/blob/master/src/tetgen.jl. 

It would be really cool if we had a metapackage that did N-Dimensional Voronoi/Delaunay and we can choose the best default implementation (Triangle for 2D, Tetgen for 3D, QHull for ND, etc.). It may make it easier for newcomers if we export a function similar to matlab `delaunayn`and `voronoin` as well. I noticed once I added `isosurface` as an API to Meshing.jl the traffic dramatically increased I presume since matlab has the same API and name.  

@konsim83 if you are interested in refinement, TetWild may be good to look at (through it requires CGAL).

**Comment by j-fu** [comment]
Hi, yes, this is a good idea. There is already VoronoiDelaunay.jl, which by its very name suggests that one might find these functions there, but it appears to 2D only (but appearantly with a good algorithm).

For my purposes I need  boundary conforming triangulations of a given domain, so the Delaunay triangulation of pointset is not sufficient. So I intend to focus on this case, see VoronoiFVM.jl, it
might end up with a kind of a metapackage for this case, which also would be useful for finite elements etc.

**Comment by sjkelly** [comment]
Tesselations.jl?

**Comment by j-fu** [comment]
> Btw, @sjkelly might be interested in this as well :)
> Would be great to move it to JuliaGeometry!

Hi @SimonDanisch , missed you today...
How to move this to JuliaGeometry (as TriangulateIO) ? I would like to register this ASAP and move on with the BinaryBuilder stuff (which I'd like to test based on the final URL).

**Comment by SimonDanisch** [comment]
I'll add you to JuliaGeometry!

**Comment by SimonDanisch** [comment]
Btw, I invited you to JuliaGeometry ;)

**Comment by SimonDanisch** [comment]
Let me know if you need any assistance!

**Comment by j-fu** [comment]
> Let me know if you need any assistance!

Yeah thanks for the invitation! Need to grab some time for this...
This is the plan:
- I create TriangulateIO.jl in JuliaGeometry
- I push all the content of TriangleRaw.jl over there
- Rename everything from TriangleRaw to TriangulateIO
- Register as v0.1.0
- Put TriangleRaw into archive mode.

At this point binary artifacts will be compiled upon installation which seems to work reasonably well on Linux, Mac, but not on Windows

- Set up BinaryBuilder for the new artifact system.  I assume that this must be run under 1.3, but resulting artifacts can be used from 1.0 upwards. If this is not the case I would try to keep the compilation intact for <1.3
- Update version, announce

Any suggestions for modification ?

Oh and I would love to see @furio and @konsim83 as coauthors there.

Jürgen

**Comment by SimonDanisch** [comment]
What is happening on windows?

**Comment by j-fu** [comment]
> What is happening on windows?

Currently nothing. There is deactivated code for VS code 2013 from Triangle.jl which probably could be tweaked somehow but still would depend on the fact that the user has a compiler installed. 

I assume the reasonable solution will be the cross-compiled artifact created via BinaryBuilder. This should be straightforward as Triangle has no dependencies besides libm and libc. 
Once it's there I will be able to test this on a  Win10 VM  and could ask my students to check it as well.

**Comment by SimonDanisch** [comment]
If you set up the BinaryBuilder, you should be able to see if it just compiles - which should be the case in such a simple case... If you have that, let me know, I can also test on windows!

**Comment by furio** [comment]
> 
> 
> > What is happening on windows?
> 
> Currently nothing. There is deactivated code for VS code 2013 from Triangle.jl which probably could be tweaked somehow but still would depend on the fact that the user has a compiler installed.
> 
> I assume the reasonable solution will be the cross-compiled artifact created via BinaryBuilder. This should be straightforward as Triangle has no dependencies besides libm and libc.
> Once it's there I will be able to test this on a Win10 VM and could ask my students to check it as well.

Yeah, that's the only solution that doesn't require having a compiler installed on your local Win machine (it caused grief also for students @ my uni xD )
BinaryBuilder is probably the only solution

**Comment by SimonDanisch** [comment]
BinaryBuilder should in all cases be preferred ;) So it shouldn't be the question if one should use BinaryBuilder, but instead when do we have the time to do it :D

**Comment by j-fu** [comment]
Let's continue this on [JuliaGeometry/Triangulate.jl](https://github.com/JuliaGeometry/Triangulate.jl/issues/1).
